### ISSUE TITLE
Log service is not sending email

### ISSUE THREAD

**Issue by davidchengIC** [bigassforce/streams#1]
I'm trying the "Simplest Possible Thing" exercise but I'm not receiving any email.  I'm in a developer edition, I entered my email address in the service config, I've checked Email Deliverability and my spam folder, and also looked in the Email Log.  Anything else I should check?

**Comment by bigassforce** [comment]
Two separate things to try:

1) Check for errors:
- navigate to Streams tab,
- display the Exceptions list view,
- was there an error processing any events?

2) Try again using default email:
- navigate to Services tab
- configure the Debug service with blank email
- try again, does it sends to your current running user?

Let us know how you get along with the results.

**Comment by davidchengIC** [comment]
There are no exceptions.  I tried a blank email in the config and it still didn't work.

**Comment by bigassforce** [comment]
If you switch to the **All** list view, does it show your events processed successfully?

**Comment by davidchengIC** [comment]
Here's the JSON from a Log event that was successfully processed even though Email Deliverability was set to no access.

FYI - this is a fairly old developer org that was set up in 2014, don't know if that makes a difference.

`{
"_config" : [ "logEmail" ],
"correlationKey" : "V23FWP",
"correlationSequence" : 1,
"genesisHops" : 1,
"genesisKey" : "SW9RS1",
"logEmail" : "",
"service" : "ETL.LogService",
"streamId" : "a1J1Y00000eIuH2UAK",
"submissionDate" : "2018-09-17T16:51:17.686+0000",
"submissionUrl" : "https://clarity1-dev-ed--etl.na88.visual.force.com/apex/etl__ServiceView?service=ETL.LogService&version=V1537195208",
"submissionUserId" : "005i0000002rY05AAE",
"version" : "V1537195208"
}`

**Comment by bigassforce** [comment]
Awesome, thanks!

Just tried the service out with a few email providers and found one that disappeared like yours.<br />It looks like the autoproc "From" address could be **_particularly_** bad in terms of spam scoring.<br />This is how Salesforce sends emails when running under the Automated Process user context:

![screen shot 2018-09-17 at 19 38 37](https://user-images.githubusercontent.com/6777144/45642838-61f19480-bab1-11e8-858b-e3ed9d89dc1f.png)

Investigating this. In the meantime it may be easier to look at the raw events in the org for debugging.

**Comment by davidchengIC** [comment]
Thanks, I installed the new package build and I do receive the email now.

However, I noticed that if I set Email Deliverability to No Access, the Event is still marked as Processed and no exception is created.  Would you like me to open a separate issue for that?

**Comment by bigassforce** [comment]
Unfortunately that's standard SF email behaviour when setting the target object ID as a user.  Even the send email result object shows success =  true.

To catch bad sends properly, we could use `setToAddresses(...)` instead but that has governor limit implications as opposed to the User ID. Which is worse? 🤔

**Comment by davidchengIC** [comment]
Gotcha, I had thought no email deliverability was supposed to generate an error, but I misunderstood.  Thanks for your help!

**Comment by JodieM** [comment]
It would be great if you can add to the Wiki to set email deliverability to All Email if you are testing this in a sandbox. I got caught on this one too.
