### ISSUE TITLE
Tutorial on cloning doesn't work as expected?

### ISSUE THREAD

**Issue by davidchengIC** [bigassforce/streams#2]
When I click Clone, there's a spinner for a second but then nothing else changes I don't see an Activate button appear.
https://github.com/bigassforce/streams/wiki/System-Versioning-Tutorial

**Comment by bigassforce** [comment]
Quick question - is this Lightning or Classic, and which browser?

**Comment by davidchengIC** [comment]
I've tried both Lightning and Classic on Chrome and Firefox on OS X.

**Comment by davidchengIC** [comment]
![screen shot 2018-09-18 at 6 51 56 am](https://user-images.githubusercontent.com/17989412/45692402-8aa87700-bb0f-11e8-8bc5-1c1fe3cf868e.png)

**Comment by bigassforce** [comment]
Fixed! New package version is linked in the Wiki.

Caused by salesforce bug: action support broken in Firefox:

```
<apex:page standardController="Account">
<apex:form id="content">
<apex:pageMessages />
<!-- works fine -->
<apex:inputText html-placeholder="Click Here">
<apex:actionSupport event="onclick" action="{!save}" /> 
</apex:inputText>
<!-- does not work in Firefox v62 -->
<apex:commandButton value="Click Here">
<apex:actionSupport event="onclick" action="{!save}" /> 
</apex:commandButton>
</apex:form>
</apex:page>
```

Workaround implemented to avoid use of action support.
