### ISSUE TITLE
Please add an Extra Step to the Install section of the Wiki

### ISSUE THREAD

**Issue by JodieM** [bigassforce/streams#4]
Can you please add the steps to 
* Switch to Classic
* Open the Streams tab
* Ignore the error message saying Not Authorized
* Click the link to perform the post install steps. 

Nothing shows in Lightning.

**Comment by bigassforce** [comment]
Fixes for #7 address this

**Comment by ohadios** [comment]
I just installed the latest package, and was still unable to run the post install configuration when on lightning... I should have captured the error details, but I didn't... :/
It worked perfectly on Classic.

**Comment by bigassforce** [comment]
Post install steps eliminated, configuration page removed
