### ISSUE TITLE
Can't drag and drop

### ISSUE THREAD

**Issue by JodieM** [bigassforce/streams#5]
Not sure what I'm doing wrong but I can't drag and drop. I use Chrome but I also tried in Firefox. I had to edit the XML document and re-upload it to get it to work.

**Comment by JodieM** [comment]
Even if I Clone the Sagas and try to edit the Saga, I still can't drag and drop.

**Comment by JodieM** [comment]
Hmm, I am sure it is something to do with Lightning just not working, as I can see your examples are using Lightning. I just am not seeing anything in Lightning at all. It is probably to do with one of the critical updates around visualforce pages. I can see the Monitor page but no other pages - clicking on the Tab just shows the blank page. 

Ah, OK, I turned off the three Critical Updates relating to Visualforce and the Pages are now working in Lightning (I will raise a new issue). But drag and drop still not working.

**Comment by JodieM** [comment]
Tried to create a brand new Saga in a new version in Lightning and nope, still does not work.

**Comment by bigassforce** [comment]
Appreciate your diligence @JodieM -- quick question, is it a 45.0 pre release org?

**Comment by JodieM** [comment]
Nope, sorry, it's a current Winter '19 Sandbox.

**Comment by bigassforce** [comment]
Fix will replace the reorderable grid with a reorderable dropdown as follows:

![screen shot 2019-01-11 at 01 50 45](https://user-images.githubusercontent.com/6777144/51008384-76b3d580-1543-11e9-9333-26d1290ef9f1.png)

**Comment by bigassforce** [comment]
Fixed in current release
