### ISSUE TITLE
Email Deliverability in the Sandbox

### ISSUE THREAD

**Issue by JodieM** [bigassforce/streams#6]
It would be great if you can add to the Wiki to set email deliverability to All Email if you are testing this in a sandbox. I got caught on this one too.

_Originally posted by @JodieM in https://github.com/bigassforce/streams/issues/1#issuecomment-449916546_

**Comment by bigassforce** [comment]
Fix will test deliverability in the log service:

```
//this checks org deliverability settings
Messaging.reserveSingleEmailCapacity(1);
```

![deliver-nag](https://user-images.githubusercontent.com/6777144/50749479-fdf90480-1236-11e9-81e4-8121572faaae.png)

**Comment by JodieM** [comment]
Nice one! Thanlks!
