### ISSUE TITLE
Allow VF pages to work in Lightning with Critical Updates Activated

### ISSUE THREAD

**Issue by JodieM** [bigassforce/streams#7]
The three Critical Updates relating to Visualforce pages in Lightning restrict this app from working in Lightning. I can not open any tab except for montoring. 

* Add a Namespace Prefix to Query Parameters and pageReference.state Properties
* Remove Instance Names From URLs for Visualforce, Community Builder, Site.com Studio, and Content Files
* Stabilize the Hostname for My Domain URLs in Sandboxes

I haven't tried all combinations I just deactivated all three, and it worked. But I have another managed package that requires the second two to function.

**Comment by JodieM** [comment]
Ah, the Services button is not working in Firefox, so I don't know if that is related at all (no, I don't have any plugins in firefox). Not sure if it's a different issue though.

**Comment by bigassforce** [comment]
Thanks, investigating.

**Comment by bigassforce** [comment]
Found a Winter '19 sandbox that reproduces this issue.
Fix will attempt to namespace prefix  all URL parameters.
