### ISSUE TITLE
Events are not moving pass Enqueued status

### ISSUE THREAD

**Issue by mdivina** [bigassforce/streams#8]
All of the Streams are stuck in Enqueued status.  Even simple events like ETL.TerminateService don’t get pass Enqueued status.  Am I missing some configuration to get them to process?  I couldn’t find any post-install configuration steps in the Wiki.

**Comment by bigassforce** [comment]
Thanks, will investigate

**Comment by mdivina** [comment]
Here's a log of the Monitor class in case that helps: 
[apex-07L1b000009eOwyEAE.log](https://github.com/bigassforce/streams/files/3015118/apex-07L1b000009eOwyEAE.log)

**Comment by bigassforce** [comment]
@mdivina logs look OK -- please can you:
1. Visit setup, Custom Settings > ETL.Application > Manage, and post a screenshot?
2. Create a temporary user with email: `support@xbaf.com` if you want an extra pair of eyes.

**Comment by mdivina** [comment]
Here you go:

![2019-03-28](https://user-images.githubusercontent.com/7283378/55174268-5951d900-513a-11e9-8143-28fb320a322c.png)

I'll create a temporary if the screenshot doesn't help.  Thank you.

**Comment by bigassforce** [comment]
@mdivina Setttings look like the post install ran OK -- does this org have IP restrictions?

**Comment by mdivina** [comment]
@bigassforce - Yes, do I know have to open up an IP on Network Access or Profile Login?

**Comment by bigassforce** [comment]
Yes - if you want a second pair of eyes, our office IP address is `77.44.110.206`

*(If you haven't already, please OK our sandbox access with management first)*

**Comment by mdivina** [comment]
@bigassforce - Are you available to get on a WebEx?  Our client would require an NDA if we created you a user in their Sandbox.  Or if you can send me some checklist to double check that Streams is configured correctly?

**Comment by bigassforce** [comment]
@mdivina Sure, support@xbaf.com

**Comment by mdivina** [comment]
@bigassforce - Please let me know if there's a good time today.  Thanks.

**Comment by bigassforce** [comment]
@mdivina Now is good

**Comment by mdivina** [comment]
@bigassforce - https://www.uberconference.com/mdivina

**Comment by mdivina** [comment]
@bigassforce - Hi, Were you able to get a response from Salesforce about that Platform Event issue we found on the webex.  I emailed the screenshot and details to support@xbaf.com after the call.

**Comment by bigassforce** [comment]
@mdivina Received below Tier 2 support response today:

> 19/04/2019 3:33 PM
> 
> I tried searching our server logs for the transaction associated with Autoproc__e and could see the last transaction happened is on 16th April and from our server logs I could see the below error message
> 
> **NoDataFoundException: c:MapFlowAction does not exist**

Could this be a component referenced in the sandbox org?

When happens in Setup > Apex Classes when clicking Compile All?

**Comment by mdivina** [comment]
@bigassforce - There's geopointe:MapFlowAction but not c:MapFlowAction.  Why would Autoproc__e need either?

Results of Compile All:
Compilation Complete
Compilation Errors found:
TC_LoanApplicationCtrlTest: line 329, column 32: Method does not exist or incorrect signature: void saveEquipment(List<Equipment__c>, String) from the type TC_LoanApplicationCtrl
TC_PaynetRelatedPartiesProcessBuilder: line 9, column 16: Illegal assignment from List<String> to String

Don't think those are related either to Autoproc__e.  Any other ideas?

**Comment by bigassforce** [comment]
It sounds totally unrelated but I've seen one invalid class affect all other classes. Would it be possible to hunt down and resolve the broken reference until Compile All Classes resolves OK? @mdivina

**Comment by mdivina** [comment]
@bigassforce - Ok, I got it to:

info	
Compilation Complete
Compilation Successful

Then uninstalled Streams, reinstalled Streams.  When I go the Autoproc after reinstalling it still has Latest Published Id = -1.  When I enqueued a Streaming event nothing happens as before and Published Id = -1 still.

**Comment by bigassforce** [comment]
@mdivina Thanks -- will fillow up with SF support response.

**Comment by bigassforce** [comment]
Platform event dependency removed
